"use strict";
const TYPES=[
 {id:"lifestyle",name:"Lifestyle Startup",short:"Проект поддерживает выбранный образ жизни основателя."},{id:"small",name:"Small-Business Startup",short:"Малая компания решает локальную потребность."},{id:"scalable",name:"Scalable Startup",short:"Проект рассчитан на быстрый рост и глобальный рынок."},{id:"buyable",name:"Buyable Startup",short:"Продукт создают с расчётом на последующую продажу."},{id:"large",name:"Large-Company Startup",short:"Новый продукт запускает крупная компания."},{id:"social",name:"Social Startup",short:"Главная цель связана с общественно значимой проблемой."},{id:"creative",name:"Creative Startup",short:"Проект создаёт продукт в сфере творчества или медиа."}
];
const DRAG_CASES=[
 {id:"scalable",text:"Платформа проверки текста сразу проектируется для миллионов пользователей и нескольких стран."},{id:"social",text:"Приложение бесплатно помогает мигрантам понимать документы и получать доступ к важным услугам."},{id:"large",text:"Международная корпорация создаёт внутри отдельную команду для нового сервиса машинного перевода."},{id:"small",text:"Команда запускает сервис устного перевода для мероприятий в одном городе."}
];
const COMICS=[
 {id:"buyable",image:"assets/comic-buyable.webp",alt:"Команда показывает языковой модуль представительнице крупной платформы",dialogue:"— Доведём модуль перефразирования до работающего продукта и предложим его крупной образовательной платформе.",description:"Небольшая команда изначально рассматривает приобретение проекта крупным игроком как желаемый результат.",why:"Команда создаёт продукт с расчётом на последующую продажу — это Buyable Startup."},
 {id:"lifestyle",image:"assets/comic-lifestyle.webp",alt:"Преподаватель ведёт онлайн-разговорный клуб из кафе у моря",dialogue:"— Мне нужен устойчивый онлайн-клуб, который позволит преподавать и путешествовать. Глобальная экспансия не является целью.",description:"Основательница связывает проект прежде всего с предпочитаемым образом жизни.",why:"Проект поддерживает выбранный образ жизни основателя — это Lifestyle Startup."},
 {id:"social",image:"assets/comic-social.webp",alt:"Волонтёры демонстрируют мигрантам приложение для понимания документов",dialogue:"— Приложение будет бесплатно объяснять документы и помогать людям получать необходимые услуги.",description:"В центре проекта находится доступ к важной информации для уязвимой аудитории.",why:"Доминирующая цель — решение общественно значимой проблемы, поэтому это Social Startup."},
 {id:"creative",image:"assets/comic-creative.webp",alt:"Команда создаёт платформу интерактивных историй с персонажами и разветвлённым сюжетом",dialogue:"— Авторы смогут придумывать персонажей, строить разветвлённые сюжеты и создавать диалоги на разных языках.",description:"Команда объединяет технологии, сторителлинг, иллюстрацию и языковое творчество в новом медиапродукте.",why:"В основе продукта находятся творчество, истории и медиа — это Creative Startup."}
];
const RAPID=[
 {q:"Команда разрабатывает продукт специально для продажи крупному игроку.",a:"buyable",why:"Цель проекта связана с последующим приобретением."},{q:"Новый языковой сервис создаётся как отдельная инициатива внутри корпорации.",a:"large",why:"Проект запускает крупная компания."},{q:"Продукт рассчитан на быстрый выход на международный рынок.",a:"scalable",why:"Ключевой признак — масштабируемый рост."},{q:"Главная цель проекта — решить общественно значимую языковую проблему.",a:"social",why:"Социальный эффект определяет стратегию."}
];
const freshMissions=()=>[
 {selected:[],checked:false,score:0},{placements:{},selectedCard:null,checked:false,score:0},{index:0,answers:Array(4).fill(null),checked:Array(4).fill(false),score:0,complete:false},{scale:1,goal:1,origin:0,complete:false,score:0},{index:0,answers:Array(4).fill(null),checked:Array(4).fill(false),score:0,complete:false}
];
const state={mission:0,sound:true,missions:freshMissions()},$=s=>document.querySelector(s),stage=$("#stage"),scoreLabel=$("#scoreLabel");
function totalScore(){return state.missions.reduce((sum,m)=>sum+m.score,0)}
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");window.scrollTo({top:0,behavior:"smooth"})}
function tone(freq=540,duration=.1,type="sine"){if(!state.sound)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ctx=new C(),o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.05,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+duration);o.onended=()=>ctx.close()}
function celebrate(){tone(660,.08);setTimeout(()=>tone(880,.13),90)} function fail(){tone(190,.18,"sawtooth")}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1700)}
function updateScore(){scoreLabel.textContent=`${totalScore()} очков`}
function updateProgress(){const n=state.mission+1;$("#missionLabel").textContent=`Миссия ${n} из 5`;$("#progressPercent").textContent=`${n*20}%`;$("#progressBar").style.width=`${n*20}%`}
function feedback(text,good,button=""){return `<div class="feedback ${good?"good":"bad"}"><div>${text}</div>${button?`<button id="feedbackAction" class="secondary" type="button">${button}</button>`:""}</div>`}
function head(icon,title,text){return `<div class="stage-head"><div><p class="eyebrow">Миссия ${state.mission+1}</p><h2>${title}</h2><p>${text}</p></div><div class="stage-icon">${icon}</div></div>`}
function typeButtons(selected,disabled=false){return TYPES.map(t=>`<button class="choice ${selected===t.id?"selected":""}" data-id="${t.id}" ${disabled?"disabled":""}>${t.name}</button>`).join("")}
function isComplete(i){const m=state.missions[i];return i<2?m.checked:m.complete}
function missionNav(){const prev=state.mission>0,last=state.mission===4;return `<nav class="mission-nav" aria-label="Навигация по миссиям"><button id="prevMission" class="secondary" type="button" ${prev?"":"disabled"}>← Назад</button><div class="mission-dots">${state.missions.map((m,i)=>`<button class="mission-dot ${i===state.mission?"current":""} ${isComplete(i)?"done":""}" data-mission="${i}" aria-label="Миссия ${i+1}">${i+1}</button>`).join("")}</div><button id="nextMission" class="primary" type="button">${last?"Завершить игру":"Вперёд →"}</button></nav><div id="navFeedback"></div>`}
function bindNav(){$("#prevMission").onclick=()=>goTo(state.mission-1);document.querySelectorAll(".mission-dot").forEach(b=>b.onclick=()=>goTo(+b.dataset.mission));$("#nextMission").onclick=()=>state.mission===4?attemptFinish():goTo(state.mission+1)}
function goTo(index){if(index<0||index>4)return;state.mission=index;updateProgress();render();window.scrollTo({top:0,behavior:"smooth"})}
function render(){[renderSignals,renderDrag,renderComics,renderBuilder,renderRapid][state.mission]();bindNav();updateScore()}

function renderSignals(){
 const m=state.missions[0],options=["Инновации","Высокая определённость","Поиск масштабируемой модели","Работа только по готовой схеме","Рост и изменения","Гарантированная прибыль"],right=[0,2,4];
 stage.innerHTML=`<article class="stage-card">${head("📡","Сканер признаков","Выберите три признака стартапа, отмеченные в лекции.")}<div class="choice-grid">${options.map((x,i)=>`<button class="choice ${m.selected.includes(i)?"selected":""} ${m.checked&&right.includes(i)?"correct":""} ${m.checked&&m.selected.includes(i)&&!right.includes(i)?"wrong":""}" data-i="${i}" ${m.checked?"disabled":""}><span class="choice-num">${i+1}</span>${x}</button>`).join("")}</div><div id="missionFeedback">${m.checked?feedback(m.score===20?"Точно. Стартап связан с инновациями, поиском масштабируемой модели и стремлением к росту.":"Верные признаки: инновации, поиск масштабируемой модели, рост и изменения.",m.score===20):""}</div>${m.checked?"":`<div class="stage-actions"><button id="checkSignals" class="primary" ${m.selected.length===3?"":"disabled"}>Проверить</button></div>`}${missionNav()}</article>`;
 if(!m.checked){document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{const i=+b.dataset.i;m.selected=m.selected.includes(i)?m.selected.filter(x=>x!==i):m.selected.length<3?[...m.selected,i]:m.selected;render()});$("#checkSignals").onclick=()=>{m.checked=true;m.score=right.every(x=>m.selected.includes(x))?20:10;m.score===20?celebrate():fail();render()}}
}
function renderDrag(){
 const m=state.missions[1],zones=[TYPES[1],TYPES[2],TYPES[4],TYPES[5]],placedIds=Object.values(m.placements);
 stage.innerHTML=`<article class="stage-card">${head("🧩","Сортировочный ангар","Выберите карточку, затем нажмите на подходящую область. До проверки карточки можно переносить и возвращать.")}<div class="drag-layout"><div class="drag-stack">${DRAG_CASES.map(c=>`<button class="drag-card ${m.selectedCard===c.id?"selected":""} ${placedIds.includes(c.id)?"placed":""}" data-id="${c.id}" ${m.checked?"disabled":""}>${c.text}</button>`).join("")}</div><div class="drop-grid">${zones.map(z=>{const card=DRAG_CASES.find(c=>c.id===m.placements[z.id]),status=m.checked?(m.placements[z.id]===z.id?"correct":"wrong"):"";return `<div class="drop-zone ${card?"filled":""} ${status}" data-id="${z.id}"><strong>${z.name}</strong><span>${z.short}</span>${card?`<small>${card.text}</small>${m.checked?"":`<button class="remove-card" data-zone="${z.id}" aria-label="Вернуть карточку">×</button>`}`:""}</div>`}).join("")}</div></div><div id="missionFeedback">${m.checked?feedback(`${m.score/5} из 4. ${m.score===20?"Все ситуации распределены верно.":"Сравните главную цель проекта: локальная потребность, глобальный рост, инициатива корпорации или социальная задача."}`,m.score===20):""}</div>${m.checked?"":`<div class="stage-actions"><button id="checkDrag" class="primary" ${Object.keys(m.placements).length===4?"":"disabled"}>Проверить</button></div>`}${missionNav()}</article>`;
 if(!m.checked){document.querySelectorAll(".drag-card").forEach(b=>b.onclick=()=>{if(placedIds.includes(b.dataset.id))return;m.selectedCard=m.selectedCard===b.dataset.id?null:b.dataset.id;render()});document.querySelectorAll(".drop-zone").forEach(z=>z.onclick=e=>{if(e.target.closest(".remove-card")||!m.selectedCard)return;const chosen=m.selectedCard;Object.keys(m.placements).forEach(k=>{if(m.placements[k]===chosen)delete m.placements[k]});m.placements[z.dataset.id]=chosen;m.selectedCard=null;tone(460,.06);render()});document.querySelectorAll(".remove-card").forEach(b=>b.onclick=e=>{e.stopPropagation();delete m.placements[b.dataset.zone];render()});$("#checkDrag").onclick=()=>{m.checked=true;m.score=zones.filter(z=>m.placements[z.id]===z.id).length*5;m.score===20?celebrate():fail();render()}}
}
function renderComics(){
 const m=state.missions[2],item=COMICS[m.index],selected=m.answers[m.index],checked=m.checked[m.index];
 stage.innerHTML=`<article class="stage-card">${head("💬","Комиксы стартапов","Изучите ситуацию и определите тип стартапа. Четыре кейса подряд.")}<div class="case-counter">Кейс ${m.index+1} из 4</div><figure class="comic"><img src="${item.image}" alt="${item.alt}"><figcaption><blockquote>${item.dialogue}</blockquote><p>${item.description}</p></figcaption></figure><div class="choice-grid">${typeButtons(selected,checked)}</div><div id="missionFeedback">${checked?feedback(selected===item.id?`Верно. ${item.why}`:`Правильный ответ: <strong>${TYPES.find(t=>t.id===item.id).name}</strong>. ${item.why}`,selected===item.id,m.complete?"":m.index<3?"Понятно":"Завершить миссию"):""}</div>${checked?"":`<div class="stage-actions"><button id="checkComic" class="primary" ${selected?"":"disabled"}>Проверить</button></div>`}${missionNav()}</article>`;
 if(!checked){document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{m.answers[m.index]=selected===b.dataset.id?null:b.dataset.id;render()});$("#checkComic").onclick=()=>{m.checked[m.index]=true;m.answers[m.index]===item.id?celebrate():fail();render()}}else if(!m.complete)$("#feedbackAction").onclick=()=>{if(m.index<3){m.index++;render()}else{m.complete=true;m.score=m.answers.filter((a,i)=>a===COMICS[i].id).length*5;celebrate();render()}}
}
function renderBuilder(){
 const m=state.missions[3];
 stage.innerHTML=`<article class="stage-card">${head("🛠️","Конструктор стратегии","Изменяйте параметры и наблюдайте, как меняется наиболее вероятный тип проекта.")}<div class="builder"><div class="builder-row"><label for="scale">Масштаб рынка</label><input id="scale" type="range" min="0" max="2" value="${m.scale}" step="1"><div class="scale-labels"><span>локальный</span><span>национальный</span><span>глобальный</span></div></div><div class="builder-row"><label for="goal">Главная цель</label><input id="goal" type="range" min="0" max="2" value="${m.goal}" step="1"><div class="scale-labels"><span>образ жизни</span><span>общественная польза</span><span>быстрый рост</span></div></div><div class="builder-row"><label for="origin">Где возник проект</label><input id="origin" type="range" min="0" max="1" value="${m.origin}" step="1"><div class="scale-labels"><span>независимая команда</span><span>крупная компания</span></div></div></div><div id="profile" class="profile-output"></div>${m.complete?feedback("Связь между целью, масштабом и происхождением проекта исследована.",true):`<div class="stage-actions"><button id="builderDone" class="primary">Я понял связь</button></div>`}${missionNav()}</article>`;
 function update(){m.scale=+$("#scale").value;m.goal=+$("#goal").value;m.origin=+$("#origin").value;let t=m.origin?TYPES[4]:m.goal===0?TYPES[0]:m.goal===1?TYPES[5]:m.scale===2?TYPES[2]:TYPES[1];$("#profile").innerHTML=`Вероятный профиль: <strong>${t.name}</strong><br>${t.short} Один проект может сочетать несколько признаков, поэтому тип выбирают по доминирующей цели и стратегии.`}
 ["scale","goal","origin"].forEach(id=>$(`#${id}`).oninput=update);update();if(!m.complete)$("#builderDone").onclick=()=>{m.complete=true;m.score=20;celebrate();render()}
}
function renderRapid(){
 const m=state.missions[4],item=RAPID[m.index],selected=m.answers[m.index],checked=m.checked[m.index];
 stage.innerHTML=`<article class="stage-card">${head("⚡","Финальный спринт","Определите тип по главной цели. После ответа внимательно прочитайте объяснение.")}<div class="case-counter">Ситуация ${m.index+1} из 4</div><div class="scenario">${item.q}</div><div class="choice-grid">${typeButtons(selected,checked)}</div><div id="missionFeedback">${checked?feedback(selected===item.a?`Верно. ${item.why}`:`Правильный ответ: <strong>${TYPES.find(t=>t.id===item.a).name}</strong>. ${item.why}`,selected===item.a,m.complete?"":m.index<3?"Понятно":"Завершить миссию"):""}</div>${checked?"":`<div class="stage-actions"><button id="checkRapid" class="primary" ${selected?"":"disabled"}>Проверить</button></div>`}${missionNav()}</article>`;
 if(!checked){document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{m.answers[m.index]=selected===b.dataset.id?null:b.dataset.id;render()});$("#checkRapid").onclick=()=>{m.checked[m.index]=true;m.answers[m.index]===item.a?celebrate():fail();render()}}else if(!m.complete)$("#feedbackAction").onclick=()=>{if(m.index<3){m.index++;render()}else{m.complete=true;m.score=m.answers.filter((a,i)=>a===RAPID[i].a).length*5;celebrate();render()}}
}
function attemptFinish(){const missing=state.missions.map((_,i)=>i).filter(i=>!isComplete(i));if(missing.length){$("#navFeedback").innerHTML=feedback(`Не завершены миссии: <strong>${missing.map(i=>i+1).join(", ")}</strong>. Перейдите к ним по номерам выше.`,false);return}finish()}
function finish(){show("#resultScreen");const n=totalScore();$("#finalScore").textContent=n;document.querySelector(".score-ring").style.setProperty("--score-angle",`${n*3.6}deg`);let title,text,badge;if(n>=85){title="Стартап вышел на орбиту";text="Вы уверенно различаете типы стартапов и связываете их с целями и стратегиями.";badge="🚀"}else if(n>=60){title="Система почти готова";text="Основные различия понятны. Повторите типы, которые определяются по цели создания и происхождению проекта.";badge="🛰️"}else{title="Нужна повторная калибровка";text="Вернитесь к лекции и сравните типы по трём вопросам: кто запускает проект, для какого рынка и с какой главной целью.";badge="🧭"}$("#resultTitle").textContent=title;$("#resultText").textContent=text;$("#resultBadge").textContent=badge;$("#resultBreakdown").innerHTML=state.missions.map((m,i)=>`<span class="tag">Миссия ${i+1}: ${m.score}/20</span>`).join("");localStorage.setItem("startupMissionBest",Math.max(n,+(localStorage.getItem("startupMissionBest")||0)));celebrate()}
function reset(){state.mission=0;state.missions=freshMissions();updateProgress();updateScore();show("#playScreen");render()}
$("#startBtn").onclick=reset;$("#restartBtn").onclick=reset;$("#soundBtn").onclick=e=>{state.sound=!state.sound;e.currentTarget.textContent=state.sound?"🔊":"🔇";e.currentTarget.setAttribute("aria-pressed",String(state.sound));e.currentTarget.title=state.sound?"Выключить звук":"Включить звук"};$("#copyBtn").onclick=async()=>{const text=`Стартап-миссия: ${totalScore()} из 100 очков.`;try{await navigator.clipboard.writeText(text);toast("Результат скопирован")}catch{toast(text)}};
